### ISSUE TITLE
want paper

### ISSUE THREAD

**Issue by huangsusan** [JunMa11/HM_DataAug#1]
Hi:
I serch your paper in google ,but no answer.Could you share your paper《Histogram Matching Augmentation for Domain Adaptation》.
Thanks very much

**Comment by vicmancr** [comment]
Hi,
Find it here: https://arxiv.org/pdf/2012.13871.pdf

**Comment by huangsusan** [comment]
hello：


Thanks.I try this method,but my back-bone is not nnUnet.The result is not bad.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JunMa11/HM_DataAug"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月13日(星期六) 凌晨2:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JunMa11/HM_DataAug] want paper (#1)





 
Hi,
 Find it here: https://arxiv.org/pdf/2012.13871.pdf
